{% set name = "spvcm" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ce331bd5d6bcb64a07c4393093f3978763cfc8764ad0737e1866f3905e6cceae

build:
  noarch: python
  number: 2
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61.0
    - setuptools-scm >=6.2
  run:
    - python >={{ python_min }}
    - numpy 
    - scipy
    - libpysal
    - spreg
    - pandas
    - seaborn

test:
  requires:
    - python {{ python_min }}
  imports:
    - spvcm

about:
  home: https://github.com/pysal/spvcm
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Gibbs sampling for spatially-correlated variance-components'
  description: |
    This is a package to estimate spatially-correlated variance components models/varying intercept 
    models. In addition to a general toolkit to conduct Gibbs sampling in Python, the package also 
    provides an interface to PyMC3 and CODA
  doc_url: https://pysal.org/spvcm
  dev_url: https://github.com/pysal/spvcm/

extra:
  recipe-maintainers:
    - jGaboardi
    - knaaptime
    - ljwolf
    - martinfleis
    - sjsrey
